local _, L = ...;

ClassStrategyCO = {};
ClassStrategyNC = {};

function InitializeStrategy()
	ClassStrategyCO = {
		[1] = {"grind",L["grind_title"],L["grind_desc"]},
		[2] = {"attack weak",L["attack_weak_title"],L["attack_weak_desc"]},
		[3] = {"attack force",L["attack_force_title"],L["attack_force_desc"]},
		[4] = {"tank",L["tank_title"],L["tank_desc"]},
		[5] = {"tank aoe",L["tank_aoe_title"],L["tank_aoe_desc"]},
		[6] = {"tank assist",L["tank_assist_title"],L["tank_assist_desc"]},
		[7] = {"dps", L["dps_title"], L["dps_desc"]},
		[8] = {"dps aoe", L["dps_aoe_title"], L["dps_aoe_desc"]},
		[9] = {"dps assist", L["dps_assist_title"],L["dps_assist_desc"]},
		[10] = {"dps debuff", L["dps_debuff_title"],L["dps_debuff_desc"]},
		[11] = {"heal",L["heal_title"],L["heal_desc"]},
		[12] = {"aoe", L["aoe_title"],L["aoe_desc"]},
		[13] = {"flee", L["flee_title"], L["flee_desc"]},
		[14] = {"fire", L["fire_title"],L["fire_desc"]},
		[15] = {"fire aoe",L["fire_aoe_title"], L["fire_aoe_desc"]},
		[16] = {"frost",L["frost_title"],L["frost_desc"]},
		[17] = {"frost aoe", L["frost_aoe_title"], L["frost_aoe_desc"]},
		[18] = {"arcane",L["arcane_title"], L["arcane_desc"]},
		[19] = {"threat",L["threat_title"],L["threat_desc"]},
		[20] = {"conserve mana", L["conserve_mana_title"],L["conserve_mana_desc"]},
		[21] = {"shadow",L["shadow_title"], L["shadow_desc"]},
		[22] = {"shadow aoe",L["shadow_aoe_title"], L["shadow_aoe_desc"]},
		[23] = {"shadow debuff", L["shadow_debuff_title"],L["shadow_debuff_desc"]},
		[24] = {"melee",L["melee_title"],L["melee_desc"]},
		[25] = {"melee aoe", L["melee_aoe_title"], L["melee_aoe_desc"]},
		[26] = {"rshadow",L["rshadow_title"],L["rshadow_desc"]},
		[27] = {"rfrost",L["rfrost_title"], L["rfrost_desc"]},
		[28] = {"rfire", L["rfire_title"],L["rfire_desc"]},
		[29] = {"barmor", L["barmor_title"], L["barmor_desc"]},
		[30] = {"bspeed",L["bspeed_title"],L["bspeed_desc"]},
		[31] = {"rnature",L["rnature_title"],L["rnature_desc"]},
		[32] = {"bhealth",L["bhealth_title"],L["bhealth_desc"]},
		[33] = {"bmana",L["bmana_title"], L["bmana_desc"]},
		[34] = {"bdps", L["bdps_title"],L["bdps_desc"]},
		[35] = {"bear", L["bear_title"], L["bear_desc"]},
		[36] = {"cat", L["cat_title"],L["cat_desc"]},
		[37] = {"cat aoe", L["cat_aoe_title"], L["cat_aoe_desc"]},
		[38] = {"caster", L["caster_title"], L["caster_desc"]},
		[39] = {"caster aoe",L["caster_aoe_title"],L["caster_aoe_desc"]},
		[40] = {"caster debuff",L["caster_debuff_title"],L["caster_debuff_desc"]},
		[41] = {"totems", L["totems_title"], L["totems_desc"]},
		[42] = {"loot", L["loot_title"], L["loot_desc"]},
		[43] = {"naxx",L["naxx_title"],L["naxx_desc"]},
	};

	ClassStrategyNC = {
		[1] = {"grind",L["grind_nc_title"],L["grind_nc_desc"]},
		[2] = {"move random",L["move_random_nc_title"],L["move_random_nc_desc"]},
		[3] = {"attack weak",L["attack_weak_nc_title"],L["attack_weak_nc_desc"]},
		[4] = {"attack force",L["attack_force_nc_title"],L["attack_force_nc_desc"]},
		[5] = {"bhealth",L["bhealth_nc_title"],L["bhealth_nc_desc"]},
		[6] = {"bmana",L["bmana_nc_title"],L["bmana_nc_desc"]},
		[7] = {"bdps",L["bdps_nc_title"],L["bdps_nc_desc"]},
		[8] = {"emote",L["emote_nc_title"],L["emote_nc_desc"]},
		[9] = {"food",L["food_nc_title"],L["food_nc_desc"]},
		[10] = {"loot",L["loot_nc_title"],L["loot_nc_desc"]},
		[11] = {"stay",L["stay_nc_title"],L["stay_nc_desc"]},
		[12] = {"follow",L["follow_nc_title"],L["follow_nc_desc"]},
		[13] = {"quest",L["quest_nc_title"],L["quest_nc_desc"]},
		[14] = {"naxx",L["naxx_nc_title"],L["naxx_nc_desc"]},
	};
end
